
language: cpp
compiler: clang
install:
- cd ..
- wget -qO- http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz | tar xvz
- export cmakeBin=$(pwd)/cmake-3.3.0-Linux-x86_64/bin/cmake
- git clone https://github.com/FlorianChevassu/APM.git
- cd Inquire_Eigen3
script:
- cd Inquire_Eigen3
- mkdir build
- cd build
- $cmakeBin ..
- make

os: linux
