
language: cpp
compiler: clang
install:
- wget -qO- http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz | tar xvz
script:
- export cmakeBin=$(pwd)/cmake-3.3.0-Linux-x86_64/bin/cmake
- cd APM_Eigen3
- mkdir build
- cd build
- $cmakeBin ..
- make

os: linux
